project_id = "sduptfgrlqpddxlmzbvf"

[functions.generate-description]
verify_jwt = false

[functions.generate-seo-title]
verify_jwt = false

[functions.perplexity-trends]
verify_jwt = false

[functions.etsy-auth]
verify_jwt = false

[functions.etsy-callback]
verify_jwt = false
